"""'user'

Revision ID: 2f6288db44a1
Revises: 5714a96e528c
Create Date: 2022-06-21 16:34:18.124041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6288db44a1'
down_revision = '5714a96e528c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category', sa.String(length=12), nullable=False))
    op.drop_column('news', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('desc', sa.TEXT(), nullable=False))
    op.drop_column('news', 'category')
    # ### end Alembic commands ###
